import Head from 'next/head';
import {
  Container,
  Flex,
  Box,
  Icon,
  Heading,
  Text,
  Image,
  Button,
  HStack,
} from '@chakra-ui/react';
import {
  IoLogoDiscord,
  IoLogoYoutube,
  IoLogoTwitter,
  IoPerson,
  IoStatsChart,
} from 'react-icons/io5';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Flex>
          <Box py="50px" px="80px" w="full">
            <Flex alignItems="center" justifyContent="space-between" mb="130px">
              <Image src="/svg/logo.svg" w="150px" h="40px" />
              <Box>
                <Icon mr="6" w={6} h={6} as={IoLogoDiscord} />
                <Icon mr="6" w={6} h={6} as={IoLogoTwitter} />
                <Icon w={6} h={6} as={IoLogoYoutube} />
              </Box>
            </Flex>
            <Heading fontSize="4xl" mb="60px">
              An NFT is a unit of data stored on a digital ledger
            </Heading>
            <Flex borderRadius="24px" bg="white" maxW="505px" mb="64px">
              <Box px="20px" py="30px" flex="1">
                <Flex align="center" justify="start" mb="4">
                  <Box
                    w="16px"
                    height="16px"
                    display="flex"
                    alignItems="center"
                    justifyContent="center"
                    bg="blue"
                    borderRadius="6px"
                    mr="2"
                  >
                    <Icon as={IoPerson} fill="white" w="8px" h="8px" />
                  </Box>
                  <Text color="#808191" fontSize="xs">
                    Scholar
                  </Text>
                </Flex>
                <Text color="number" fontSize="4xl" fontWeight="semibold">
                  101
                </Text>
              </Box>
              <Box px="20px" py="30px" flex="1" borderX="1px solid #E4E4E4">
                <Flex align="center" justify="start" mb="4">
                  <Image
                    src="/svg/message-unread.svg"
                    w="16px"
                    height="16px"
                    mr="2"
                  />
                  <Text color="#808191" fontSize="xs">
                    SLP Average
                  </Text>
                </Flex>
                <Text color="number" fontSize="4xl" fontWeight="semibold">
                  150
                </Text>
              </Box>
              <Box px="20px" py="30px" flex="1">
                <Flex align="center" justify="start" mb="4">
                  <Box
                    w="16px"
                    height="16px"
                    display="flex"
                    alignItems="center"
                    justifyContent="center"
                    bg="purple"
                    borderRadius="6px"
                    mr="2"
                  >
                    <Icon as={IoStatsChart} fill="white" w="8px" h="8px" />
                  </Box>
                  <Text color="#808191" fontSize="xs">
                    Top Player Rank
                  </Text>
                </Flex>
                <Text color="number" fontSize="4xl" fontWeight="semibold">
                  1200
                </Text>
              </Box>
            </Flex>
            <HStack maxW="505px" spacing="16px" mb="155px">
              <Button h="16" color="white" bg="primaryDark" flex="1">
                Apply Now
              </Button>
              <Button h="16" border="1px" borderColor="primaryDark" flex="1">
                Login
              </Button>
            </HStack>
            <HStack spacing="40px">
              <Image src="/img/axie-logo.png" />
              <Image src="/img/gala-logo.png" />
              <Image src="/img/treeverse-logo.png" />
            </HStack>
          </Box>
          <Box py="50px" px="80px" w="full" bg="primaryDark" color="white">
            Right
          </Box>
        </Flex>
      </main>

      <footer></footer>
    </div>
  );
}
